[package]
name = "rokku"
version = "0.1.0"
authors = ["Skyler Berg <skylertheberg@gmail.com>"]
edition = "2021"

[dependencies]
mcts = { path = "./monte_carlo" }
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
