[package]
name = "mcts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-ord = "0.3.2"
itertools = "0.11.0"
rand = "0.8.5"
rolling-stats = "0.7.0"
rustc-hash = "1.1.0"
weighted_rand = "0.4.2"
